import { ResponseBody } from "../base";

export declare type Contrato = {
    'id': number,
    'tipo': 'I' | string,
    'estrato_social_col': string,
    'id_cliente': number,
    'id_vd_contrato': string,
    'descricao_aux_plano_venda': string,
    'contrato': string,
    'id_tipo_contrato': string,
    'id_modelo': string,
    'assinatura_digital': 'P' | 'N',
    'integracao_assinatura_digital': 'P' | 'N',
    'liberacao_bloqueio_manual': 'P' | 'N',
    'id_filial': string,
    'indicacao_contrato_id': string,
    'data_assinatura': string,
    'isentar_contrato': 'S' | 'N',
    'data_ativacao': string,
    'data': string,
    'data_renovacao': string,
    'pago_ate_data': string,
    'status': 'P' | 'N',
    'status_internet': 'D' | 'N',
    'status_velocidade': 'N' | 'V' | 'S',
    'tipo_produtos_plano': 'P' | 'N',
    'motivo_inclusao': 'I' | 'N',
    'id_indexador_reajuste': string,
    'url_assinatura_digital': string,
    'token_assinatura_digital': string,
    'id_tipo_documento': string,
    'id_carteira_cobranca': string,
    'id_vendedor': string,
    'moeda': string,
    'comissao': string,
    'cc_previsao': 'P' | 'N',
    'tipo_cobranca': 'P' | 'N',
    'renovacao_automatica': 'S' | 'N',
    'gerar_finan_assin_digital_contrato': 'P' | 'N',
    'base_geracao_tipo_doc': 'P' | 'N',
    'id_contrato_principal': string,
    'num_parcelas_atraso': string,
    'nf_info_adicionais': string,
    'credit_card_recorrente_bandeira_cartao': string,
    'credit_card_recorrente_token': string,
    'ids_contratos_recorrencia': string,
    'tipo_doc_opc': string,
    'tipo_doc_opc2': string,
    'tipo_doc_opc3': string,
    'tipo_doc_opc4': string,
    'id_tipo_doc_ativ': string,
    'id_produto_ativ': string,
    'taxa_instalacao': string,
    'id_cond_pag_ativ': string,
    'id_responsavel': string,
    'id_vendedor_ativ': string,
    'ativacao_numero_parcelas': string,
    'ativacao_vencimentos': string,
    'btn_nf_ativacao': string,
    'ativacao_valor_parcela': string,
    'fidelidade': string,
    'data_expiracao': string,
    'dica_data_expiracao': string,
    'desconto_fidelidade': string,
    'id_instalador': string,
    'taxa_improdutiva': string,
    'venc_personalizado': string,
    'com_entrada': string,
    'dia_fixo_vencimento': string,
    'tipo_condicao_pag': string,
    'bloqueio_automatico': 'S' | 'N',
    'nao_bloquear_ate': string,
    'aviso_atraso': 'S' | 'N',
    'nao_avisar_ate': string,
    'desbloqueio_confianca': 'P' | 'N',
    'desbloqueio_confianca_ativo': 'N' | 'S',
    'restricao_auto_desbloqueio': 'N' | 'S',
    'motivo_restricao_auto_desbloq': string,
    'obs': string,
    'nao_susp_parc_ate': string,
    'liberacao_suspensao_parcial': 'P' | 'N',
    'utilizando_auto_libera_susp_parc': 'N' | 'S',
    'restricao_auto_libera_susp_parcial': 'N' | 'S',
    'motivo_restri_auto_libera_parc': string,
    'contrato_suspenso': 'N' | 'S',
    'data_inicial_suspensao': string,
    'data_final_suspensao': string,
    'data_acesso_desativado': string,
    'data_cancelamento': string,
    'id_responsavel_cancelamento': string,
    'motivo_cancelamento': string,
    'motivo_adicional': string,
    'concorrente_mot_adicional': string,
    'dica_motivo_adicional_cliente_contrato': string,
    'obs_cancelamento': string,
    'data_negativacao': string,
    'id_responsavel_negativacao': string,
    'protocolo_negativacao': string,
    'id_motivo_negativacao': string,
    'obs_negativacao': string,
    'data_desistencia': string,
    'id_responsavel_desistencia': string,
    'motivo_desistencia': string,
    'obs_desistencia': string,
    'obs_contrato': string,
    'alerta_contrato': string,
    'imp_realizado': 'S' | 'N',
    'imp_inicial': string,
    'imp_carteira': 'N' | 'S',
    'imp_importacao': 'N' | 'S',
    'imp_treinamento': 'N' | 'S',
    'imp_rede': 'N' | 'S',
    'imp_bkp': 'N' | 'S',
    'imp_obs': string,
    'imp_final': string,
    'imp_status': 'A' | 'I',
    'imp_motivo': string,
    'dt_ult_bloq_auto': string,
    'dt_ult_bloq_manual': string,
    'dt_ult_finan_atraso': string,
    'dt_ult_des_bloq_conf': string,
    'dt_ult_liberacao_susp_parc': string,
    'dt_ult_ativacao': string,
    'dt_utl_negativacao': string,
    'dt_ult_desiste': string,
    'data_cadastro_sistema': string,
    'ultima_atualizacao': string,
    'data_retomada_contrato': string,
    'endereco_padrao_cliente': 'S' | 'N',
    'endereco_padrao_alert': string,
    'id_condominio': string,
    'condominio_novo': string,
    'bloco': string,
    'bloco_novo': string,
    'apartamento': string,
    'apartamento_novo': string,
    'cep': string,
    'cep_novo': string,
    'endereco': string,
    'endereco_novo': string,
    'numero': string,
    'numero_novo': string,
    'bairro': string,
    'bairro_novo': string,
    'cidade': string,
    'cidade_novo': string,
    'complemento': string,
    'complemento_novo': string,
    'referencia': string,
    'referencia_novo': string,
    'latitude': string,
    'latitude_novo': string,
    'longitude': string,
    'longitude_novo': string,
    'tipo_localidade': 'U' | 'R',
    'avalista_1': string,
    'avalista_2': string,
    'testemunha_assinatura_digital': string,
    'document_photo': 'P' | 'N',
    'selfie_photo': 'P' | 'N'
};

export declare type ContratoResponse = ResponseBody<Contrato>;

export declare type ContratoAttrs = keyof Contrato;